version: '3.1'

services:
  db:
      container_name: apolo_db
      image: mysql
      command: --default-authentication-plugin=mysql_native_password
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: pass
        MYSQL_DATABASE: users
        MYSQL_USER: dev
        MYSQL_PASSWORD: dev-password
      ports:
        - "3306:3306"